export const vehicleChecklist = [
  "Neumáticos en buen estado",
  "Luces delanteras y traseras",
  "Sistema de frenos",
  "Nivel de aceite",
  "Nivel de refrigerante",
  "Espejos retrovisores",
  "Bocina",
  "Limpiaparabrisas",
  "Cinturones de seguridad",
  "Documentación vigente",
  "Botiquín",
  "Extintor",
  "Triángulos de seguridad",
];